fix: Add spacing for list selection
SAP/fundamental-styles pull request #1569
Opened 2020-09-02 15:43 UTC by JKMarkowski

## Related Issue
Closes #1544 

## Description
There is increased padding for selection list, on compact mode.

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:
![image](https://user-images.githubusercontent.com/26483208/92005433-c613ce80-ed43-11ea-985a-dccfb6e84050.png)

### After:

#### Please check whether the PR fulfills the following requirements

- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

2020-09-03 14:59 UTC, jessmetivier approved these changes
LGTM

2020-09-03 15:23 UTC, InnaAtanasova commented
<img width="499" alt="Screen Shot 2020-09-03 at 11 21 41 AM" src="https://user-images.githubusercontent.com/39598672/92134692-d5dcf280-edd7-11ea-8082-4e7b657f1bcd.png">

I think the checkbox should be centered inside the touchable area

2020-09-04 08:53 UTC, salarenko requested changes
Currently checkbox left offset is `0.5rem + 0.375rem`, should be `1rem`

2020-09-10 15:20 UTC, InnaAtanasova approved these changes

2020-09-11 09:50 UTC, salarenko approved these changes

2020-09-11 09:50 UTC, merged