feat: Apply icons changes to tree
SAP/fundamental-styles pull request #1643
Opened 2020-09-17 11:28 UTC by JKMarkowski

## Related Issue
Related to https://github.com/SAP/fundamental-styles/issues/1603

## Description
Breaking Change:
- Now Tree expander requires navigation icon
Before:
```
<button tabindex="0" class="fd-tree__expander" aria-label="Expander"></button>
```

After:
```
<button tabindex="0" class="fd-tree__expander" aria-label="Expander">
     <i class="sap-icon--navigation-right-arrow" role="presentation"></i>
</button> 
```

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

#### Please check whether the PR fulfills the following requirements

- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

2020-09-17 18:20 UTC, mikerodonnell89 commented
Something I noticed in the "Tree With Expanded Level 6 And Navigation Links" section, if you click right on the icon, the blue cuts in to the semantic coloring on the left

![Screen Shot 2020-09-17 at 12 16 39 PM](https://user-images.githubusercontent.com/2471874/93511330-de592100-f8df-11ea-8a61-95b5e9bcfa3a.png)

2020-09-17 18:20 UTC, mikerodonnell89 commented
RTL buttons sized weird

![Screen Shot 2020-09-17 at 12 20 07 PM](https://user-images.githubusercontent.com/2471874/93511482-22e4bc80-f8e0-11ea-97e6-d29e16fd1646.png)

2020-09-17 18:21 UTC, mikerodonnell89 requested changes
Code looks good, just two small bugs, see above

2020-09-21 10:26 UTC, JKMarkowski commented
@mikerodonnell89 Those bugs have been addressed. It's ready for second check

2020-09-22 13:43 UTC, InnaAtanasova approved these changes

2020-09-22 13:50 UTC, salarenko approved these changes

2020-09-22 14:38 UTC, mikerodonnell89 approved these changes

2020-09-22 16:26 UTC, merged