fix: Refactor object status icons and text
SAP/fundamental-styles pull request #1655
Opened 2020-09-17 13:17 UTC by JKMarkowski

## Related Issue
related to https://github.com/SAP/fundamental-styles/issues/1603

## Description
There are added 2 new elements:
`fd-object-status__icon` and `fd-object-status__text`

It brings breaking change:
Before:
```
<span class="fd-object-status sap-icon--to-be-negative">Negative</span>
```

After:
```
<span class="fd-object-status fd-object-status--negative">
    <i class="fd-object-status__icon sap-icon--status-negative" role="presentation"></i>
    <span class="fd-object-status__text">Negative</span>
</span>
```

#### Please check whether the PR fulfills the following requirements

- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

2020-09-21 20:34 UTC, jessmetivier requested changes
The object status icons look different...

Aren't these are the icons for Fiori 3?
![Screen Shot 2020-09-21 at 4 33 14 PM](https://user-images.githubusercontent.com/57453945/93818279-294c9e80-fc28-11ea-9c42-1209e9fc9376.png)

2020-09-22 13:45 UTC, JKMarkowski commented
> The object status icons look different...
> 
> Aren't these are the icons for Fiori 3?
> ![Screen Shot 2020-09-21 at 4 33 14 PM](https://user-images.githubusercontent.com/57453945/93818279-294c9e80-fc28-11ea-9c42-1209e9fc9376.png)

@jessmetivier We are taking SAP icons, not fiori 3, so they can differ a little bit

2020-09-22 14:01 UTC, salarenko approved these changes

2020-09-22 15:32 UTC, jessmetivier approved these changes

2020-09-22 16:41 UTC, merged