fix: Table, List - Refactor icons usage - #2
SAP/fundamental-styles pull request #1677
Opened 2020-09-21 12:27 UTC by salarenko

## Related Issue
Successor of: #1651
Part of: #1603

## Description
This PR:
- Moves byline list thumbnail icon into separate element
- Updates table icon styling with icon mixins and adds aria labels
- Updates list icon styling with icon mixins and adds aria labels

List:
### Before:
```
 <li role="listitem" tabindex="0" class="fd-list__item">
      <span class="sap-icon--activate fd-list__thumbnail"></span>
</li>
```

### After:
```
 <li role="listitem" tabindex="0" class="fd-list__item">
      <span class="fd-list__thumbnail"><i class="sap-icon--activate" role="presentation"></i></span>
</li>
```

Table:
### Before:
```
<td class="fd-table__cell fd-table__cell--fit-content fd-table__cell--no-padding">
    <span class="fd-table__icon fd-table__icon--navigation sap-icon--navigation-right-arrow"></span>
</td>
```

### After:
```
<td class="fd-table__cell fd-table__cell--fit-content fd-table__cell--no-padding">
    <i class="fd-table__icon fd-table__icon--navigation sap-icon--navigation-right-arrow" role="presentation"></i>
</td>
```

#### Please check whether the PR fulfills the following requirements

- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

2020-09-21 20:04 UTC, jessmetivier requested changes
Everything looks great, there's just one thing I noticed from the [Standard List](https://wiki.wdf.sap.corp/wiki/display/visualcore/List+%28Fiori+3%29+-+Standard+List) specs.

When certain items have icons where others do not, all of the list items still align right (as though they had icons) like this:
![Screen Shot 2020-09-21 at 3 59 56 PM](https://user-images.githubusercontent.com/57453945/93815342-cfe27080-fc23-11ea-8b64-1015fab62d1b.png)
(See E)
![Screen Shot 2020-09-21 at 4 04 55 PM](https://user-images.githubusercontent.com/57453945/93815585-349dcb00-fc24-11ea-8028-22c89e0d5835.png)

Currently, all the examples show that the items without icons shift back left
![Screen Shot 2020-09-21 at 4 02 57 PM](https://user-images.githubusercontent.com/57453945/93815419-ed173f00-fc23-11ea-96ec-ba4e508b6987.png)

2020-09-22 13:15 UTC, JKMarkowski approved these changes
LGTM

2020-09-22 13:17 UTC, JKMarkowski commented
@jessmetivier Thanks for noticing this. It should be tackled in other PR, I will create issue

2020-09-22 13:32 UTC, InnaAtanasova approved these changes

2020-09-22 15:03 UTC, merged