fix: fix examples markup and the max-width of the footer content
SAP/fundamental-styles pull request #1714
Opened 2020-09-25 19:46 UTC by InnaAtanasova

## Description
The last item of the footer (7 minutes ago) was wrapped with a span and `fd-notification__footer-content` class in all examples. The footer items were always the same size, changed the max-width to be 50%, positioning the second item close to the first one.

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:
<img width="790" alt="Screen Shot 2020-09-25 at 3 44 36 PM" src="https://user-images.githubusercontent.com/39598672/94309414-0a128180-ff46-11ea-89b1-731a6761fdf4.png">

### After:
<img width="820" alt="Screen Shot 2020-09-25 at 3 38 50 PM" src="https://user-images.githubusercontent.com/39598672/94309456-1e567e80-ff46-11ea-9dea-420410457e33.png">
<img width="835" alt="Screen Shot 2020-09-25 at 3 38 41 PM" src="https://user-images.githubusercontent.com/39598672/94309470-231b3280-ff46-11ea-957d-4ac8638cadcf.png">
<img width="445" alt="Screen Shot 2020-09-25 at 3 38 33 PM" src="https://user-images.githubusercontent.com/39598672/94309475-257d8c80-ff46-11ea-91a5-bf1730f146fc.png">

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [ ] Text elements follow the truncation rules

2. Documentation
- [ ] Storybook documentation has been created/updated

2020-09-25 20:54 UTC, droshev approved these changes

2020-09-26 03:28 UTC, prsdthkr requested changes
Probably unrelated but It'd be great if it's fixed here:
* popover in mobile is skewed down
![image](https://user-images.githubusercontent.com/43764832/94329183-91bfb680-ff6d-11ea-9f4e-2189609de65d.png)
* could we also make `fd-tabs` focusable and add focus indicator

2020-09-29 10:46 UTC, JKMarkowski approved these changes
Let's add `align-items: flex-start` to `fd-notification__actions`, to prevent from height expansion. So Popover won't behave that weird. Rest LGTM

2020-10-06 16:03 UTC, InnaAtanasova commented
Hey @prsdthkr your comments have been addressed. Could you check again? Thanks

2020-10-07 05:35 UTC, prsdthkr approved these changes
QA LGTM 🛫

2020-10-07 12:39 UTC, merged