fix: Fix compile issue for rating indicator styles
SAP/fundamental-styles pull request #1782
Opened 2020-10-14 08:51 UTC by mykolavorobiov

## Related Issue
## Description
![image](https://user-images.githubusercontent.com/38053194/95965398-8e07ad00-0e12-11eb-862c-6a3117a51acd.png)

The rating indicator can't be compiled when is used in the ngx-fundamental component.

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:
![image](https://user-images.githubusercontent.com/38053194/95963940-f5246200-0e10-11eb-9917-540b1083a3f3.png)

### After:
![image](https://user-images.githubusercontent.com/38053194/95963883-e63daf80-0e10-11eb-8a3e-e69d48f306c8.png)

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [ ] All values are in `rem`
- [ ] Text elements follow the truncation rules
- [ ] hover state of the element follow design spec
- [ ] focus state of the element follow design spec
- [ ] active state of the element follow design spec
- [ ] selected state of the element follow design spec
- [ ] selected hover state of the element follow design spec
- [ ] pressed state of the element follow design spec
- [ ] Responsiveness rules - the component has modifier classes for all breakpoints
- [ ] Includes Compact/Cosy/Tablet design
- [ ] RTL support
2. The code follows fundamental-styles code standards and style
- [ ] BEM naming convention is used
- [ ] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [ ] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [ ] `fd-reset()` mixin is applied to all elements
- [ ] Variables are used, if some value is used more than twice.
- [ ] Checked if current components can be reused, instead of having new code.
3. Testing
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] Updated tests
4. Documentation
- [ ] Storybook documentation has been created/updated
- [ ] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2020-10-14 08:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/fundamental-styles?pullRequest=1782) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/fundamental-styles?pullRequest=1782) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/fundamental-styles?pullRequest=1782) it.</sub>

2020-10-14 08:58 UTC, IlyaSurmay approved these changes

2020-10-14 09:34 UTC, EvilAlexei approved these changes

2020-10-14 12:02 UTC, katekozlowska approved these changes

2020-10-14 13:22 UTC, jbadan requested changes
We should just remove these variables - please see https://github.com/SAP/fundamental-styles/issues/1753

If we new css variables that aren't defined by sap-theming, they should go in the theming/sap*.scss files.

2020-10-15 07:56 UTC, mykolavorobiov commented
@jbadan Got it

2020-12-08 22:36 UTC, closed without merging