docs: bring popover to action bar
SAP/fundamental-styles pull request #1809
Opened 2020-10-22 10:39 UTC by JKMarkowski

## Related Issue
part of https://github.com/SAP/fundamental-styles/issues/1760

## Description
Ther is added missing popover functionality.

2020-10-22 19:05 UTC, prsdthkr requested changes
Could we keep the contextual actions popover open by default for snapshot purposes?

2020-10-22 19:05 UTC, prsdthkr commented on stories/action-bar/action-bar.stories.js
>                      <button aria-label="button"class="fd-button fd-button--transparent fd-button--compact"
```suggestion
                    <button class="fd-button fd-button--transparent fd-button--compact is-expanded"
```

2020-10-22 19:05 UTC, prsdthkr commented on stories/action-bar/action-bar.stories.js
> +                    aria-controls="wgxzK859" aria-haspopup="true" aria-expanded="false" aria-label="More"
```suggestion
                    aria-controls="wgxzK859" aria-haspopup="true" aria-expanded="true" aria-label="More"
```

2020-10-22 19:05 UTC, prsdthkr commented on stories/action-bar/action-bar.stories.js
>                          aria-controls="wgxzK85" aria-haspopup="true" aria-expanded="false" aria-label="More">
```suggestion
                        aria-controls="wgxzK85" aria-haspopup="true" aria-expanded="true" aria-label="More">
```

2020-10-23 13:16 UTC, JKMarkowski commented
Hello @prsdthkr Thanks for checking it, I applied your proposition, so action bar menus are opened by default.

2020-10-26 18:09 UTC, mikerodonnell89 approved these changes

2020-10-26 19:20 UTC, prsdthkr approved these changes
QA LGTM 🚢

2020-10-27 12:44 UTC, merged