docs: add background to busy indicator example
SAP/fundamental-styles pull request #1830
Opened 2020-10-28 16:32 UTC by InnaAtanasova

## Related Issue
Part of SAP/fundamental-styles#1760

## Description
In HCD mode the Busy Indicator was not visible as the "dots" had the same color as the background. A background color was added to the example to fix this."

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:
<img width="2086" alt="Screen Shot 2020-10-28 at 12 32 14 PM" src="https://user-images.githubusercontent.com/39598672/97466568-a353ff80-1919-11eb-83dc-6e0e4ecc598a.png">
<img width="2047" alt="Screen Shot 2020-10-28 at 12 32 03 PM" src="https://user-images.githubusercontent.com/39598672/97466596-abac3a80-1919-11eb-9878-bf0913fd81fb.png">

### After:
<img width="2079" alt="Screen Shot 2020-10-28 at 12 29 53 PM" src="https://user-images.githubusercontent.com/39598672/97466289-51ab7500-1919-11eb-824f-70b2d07fb307.png">
<img width="2016" alt="Screen Shot 2020-10-28 at 12 29 41 PM" src="https://user-images.githubusercontent.com/39598672/97466324-5b34dd00-1919-11eb-87dd-170504739004.png">

2020-10-28 17:21 UTC, prsdthkr requested changes
Can the background colors be inline with the spec examples here: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2092401791

![image](https://user-images.githubusercontent.com/43764832/97472671-4fd8b600-1907-11eb-8305-bb6db5ba1b82.png)

2020-10-29 04:45 UTC, prsdthkr commented
Maybe also this #1833

2020-10-30 16:59 UTC, InnaAtanasova commented
closing in favour of https://github.com/SAP/fundamental-styles/pull/1827

2020-10-30 16:59 UTC, closed without merging

2020-10-30 16:59 UTC, InnaAtanasova commented
> Maybe also this #1833

Will open a separate PR for this.