fix: Simplify selectors in toolbar component
SAP/fundamental-styles pull request #1851
Opened 2020-11-04 10:55 UTC by JKMarkowski

## Related Issue
Closes https://github.com/SAP/fundamental-styles/issues/1850

## Description
There is simplify of toolbar component selector. No visual changes predicted

2020-11-05 15:39 UTC, jbadan commented on src/toolbar.scss
> +  &__overflow__body {
We shouldn't have 2 block levels in a name - http://getbem.com/naming/

2020-11-05 15:39 UTC, jbadan commented on src/toolbar.scss
> +    > .#{$fd-namespace}-button {
This needs to be removed - there should be no universal selectors (`*`) ever and we should not be using `.#{$fd-namespace}-*` as discussed previously.

2020-11-05 15:39 UTC, jbadan commented on src/toolbar.scss
> +    .#{$block}__overflow__label {
Same comment as above

2020-11-05 15:40 UTC, jbadan requested changes
See comments

2020-11-19 11:09 UTC, katekozlowska requested changes

2020-11-19 11:09 UTC, katekozlowska commented on src/toolbar.scss
> +      .#{$block}__separator {
missing `fd-reset()`

2020-11-19 11:09 UTC, katekozlowska commented on src/toolbar.scss
>      .#{$block}__separator {
missing `fd-reset()`

2020-12-08 14:21 UTC, closed without merging