fix: Make stronger selector for message strip
SAP/fundamental-styles pull request #1856
Opened 2020-11-05 12:53 UTC by JKMarkowski

## Description
There is stronger selector for message-strip close element.

## Screenshots

No visual/usage changes predicted

2020-11-05 12:55 UTC, JKMarkowski commented
Chromatic detected  changes in checkbox/radio buttons. Which i guess are leftovers

2020-11-05 15:35 UTC, jbadan commented on src/message-strip.scss
> +  &__close.#{$fd-namespace}-button {
I thought we agreed not to do this in the last few meetings?

2020-11-05 15:36 UTC, jbadan requested changes
We should not mix `fd-*` classes in the same file. It breaks css modules in fundamental-react.

2020-11-10 09:48 UTC, JKMarkowski commented
> We should not mix `fd-*` classes in the same file. It breaks css modules in fundamental-react.

I just added second level of nesting, to make it stronger

2020-11-10 15:35 UTC, jbadan approved these changes

2020-11-10 21:07 UTC, droshev approved these changes

2020-11-10 21:20 UTC, merged