feat: flexible column layout
SAP/fundamental-styles pull request #1887
Opened 2020-11-16 10:56 UTC by JKMarkowski

## Related Issue
Closes SAP/fundamental-styles#1878

## Description
There is added `flexible column layout` component with delta theming and examples of usage.

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [x] Text elements follow the truncation rules
- [x] hover state of the element follow design spec
- [NA] focus state of the element follow design spec
- [NA] active state of the element follow design spec
- [NA] selected state of the element follow design spec
- [NA] selected hover state of the element follow design spec
- [NA] pressed state of the element follow design spec
- [x] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [NA] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [x] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [x] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] Updated tests
4. Documentation
- [ ] Storybook documentation has been created/updated
- [ ] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2020-11-16 21:46 UTC, InnaAtanasova requested changes

2020-11-16 21:46 UTC, InnaAtanasova commented on src/flexible-column-layout.scss
> +  $toggle-button-height: 2rem;
these 2 should have the `fd-` prefix in the naming

2020-11-16 21:46 UTC, InnaAtanasova commented on src/flexible-column-layout.scss
> +  }
maybe move this to the `_mixins.scss` file

2020-11-16 21:46 UTC, InnaAtanasova commented on src/flexible-column-layout.scss
> +    min-width: 1.5rem;
The value should be a variable

2020-11-16 21:46 UTC, InnaAtanasova commented on src/flexible-column-layout.scss
> +      bottom: calc(50% + #{$toggle-button-height} / 2);
This can be a variable and used in bottom and top

2020-11-16 21:46 UTC, InnaAtanasova commented on src/mixins/_mixins.scss
> +}
I don't think @content is appropriate in these cases

2020-11-17 14:49 UTC, JKMarkowski commented
@InnaAtanasova Thank You for checking, you comments has been addressed, could you take a look again? :)

2020-11-17 17:12 UTC, stefanoScalzo commented
![Screen Shot 2020-11-17 at 12 11 42 PM](https://user-images.githubusercontent.com/50607147/99423018-1f64b600-28ce-11eb-8a21-522834d2c148.png)
![Screen Shot 2020-11-17 at 12 11 38 PM](https://user-images.githubusercontent.com/50607147/99423020-1ffd4c80-28ce-11eb-8223-b348fa8ebb89.png)
The button is going behind

2020-11-18 11:44 UTC, katekozlowska approved these changes
Good job with this component! Only one thing - required value `min-width: 20rem,` makes presented example look broken (f.e. ratio 1:2 in two-columns layout looks incorrect), but it works fine, when I'm testing it separately on different examples.

2020-11-18 14:52 UTC, InnaAtanasova commented on src/mixins/_mixins.scss
> +@mixin both-pseudo-selectors() {
sorry, could you add `fd-` for consistency?

2020-11-18 14:53 UTC, InnaAtanasova approved these changes

2020-11-18 16:13 UTC, stefanoScalzo commented
LGTM

2020-11-18 16:13 UTC, stefanoScalzo approved these changes

2020-11-18 16:42 UTC, merged