fix: change anchor to button element on tabs
SAP/fundamental-styles pull request #1989
Opened 2020-12-21 17:39 UTC by stefanoScalzo

BREAKING CHANGES: change anchor element to button element on tab

## Related Issue
Closes SAP/fundamental-styles#105

## Description
Change the anchor element to a button element
Adds border bottom to remove the white overlapping the container border
fixes the offset on the navigation line to compensate

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [ ] All values are in `rem`
- [ ] Text elements follow the truncation rules
- [ ] hover state of the element follow design spec
- [ ] focus state of the element follow design spec
- [ ] active state of the element follow design spec
- [ ] selected state of the element follow design spec
- [ ] selected hover state of the element follow design spec
- [ ] pressed state of the element follow design spec
- [ ] Responsiveness rules - the component has modifier classes for all breakpoints
- [ ] Includes Compact/Cosy/Tablet design
- [ ] RTL support
2. The code follows fundamental-styles code standards and style
- [ ] only one top level `fd-*` class is used in the file
- [ ] BEM naming convention is used
- [ ] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [ ] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [ ] `fd-reset()` mixin is applied to all elements
- [ ] Variables are used, if some value is used more than twice.
- [ ] Checked if current components can be reused, instead of having new code.
3. Testing
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] Updated tests
4. Documentation
- [ ] Storybook documentation has been created/updated
- [ ] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2020-12-22 09:54 UTC, JKMarkowski commented
![image](https://user-images.githubusercontent.com/26483208/102875371-ffcc2a80-4443-11eb-9540-9773e2fb80aa.png)
Counters are centered here, could you check it ?

2020-12-28 13:21 UTC, JKMarkowski commented
LEt's wait for @jbadan approval

2021-01-04 20:52 UTC, InnaAtanasova requested changes
The role should not be `link`. Please check again the link provided in the issue description

2021-01-05 15:48 UTC, stefanoScalzo commented
> The role should not be `link`. Please check again the link provided in the issue description

fixed all a11y

2021-01-08 16:19 UTC, mikerodonnell89 requested changes
I believe the changes to border bottom are causing this problem with the high contrast version

![Screen Shot 2021-01-08 at 9 18 54 AM](https://user-images.githubusercontent.com/2471874/104038590-8ac25a00-5192-11eb-9f3b-8bf2524e5a84.png)

2021-01-08 16:24 UTC, mikerodonnell89 commented
Also I'm still seeing `role="link"` everywhere

2021-01-14 18:37 UTC, InnaAtanasova commented
Closing the PR, needs more work

2021-01-14 18:37 UTC, closed without merging