fix: pagination button to anchor element
SAP/fundamental-styles pull request #1990
Opened 2020-12-21 18:03 UTC by stefanoScalzo

BREAKING CHANGES: change anchor element to button element for pagination links

## Related Issue
Closes SAP/fundamental-styles#107

## Description
Change all anchor elements to button elements with role="link" for a11y

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [ ] All values are in `rem`
- [ ] Text elements follow the truncation rules
- [ ] hover state of the element follow design spec
- [ ] focus state of the element follow design spec
- [ ] active state of the element follow design spec
- [ ] selected state of the element follow design spec
- [ ] selected hover state of the element follow design spec
- [ ] pressed state of the element follow design spec
- [ ] Responsiveness rules - the component has modifier classes for all breakpoints
- [ ] Includes Compact/Cosy/Tablet design
- [ ] RTL support
2. The code follows fundamental-styles code standards and style
- [ ] only one top level `fd-*` class is used in the file
- [ ] BEM naming convention is used
- [ ] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [ ] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [ ] `fd-reset()` mixin is applied to all elements
- [ ] Variables are used, if some value is used more than twice.
- [ ] Checked if current components can be reused, instead of having new code.
3. Testing
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] Updated tests
4. Documentation
- [ ] Storybook documentation has been created/updated
- [ ] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2020-12-22 09:56 UTC, JKMarkowski commented
Code looks good to me, but is it valid way for a11y? 
https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination

2020-12-22 16:37 UTC, stefanoScalzo commented
> https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination

@jbadan Are we sure we should be changing this markup to button?

2021-01-08 15:59 UTC, mikerodonnell89 commented
I think it is fine to use button but they should have `role="navigation"` not link

2021-01-08 16:00 UTC, mikerodonnell89 requested changes
edit: removed

2021-01-11 20:48 UTC, mikerodonnell89 commented
Closing this as the original implementation is correct

2021-01-11 20:48 UTC, closed without merging