chore: update the rules for running chromatic in PRs
SAP/fundamental-styles pull request #2061
Opened 2021-01-15 01:31 UTC by droshev

## Related Issue
Closes SAP/fundamental-styles#

## Description
{{ _Enter short description of the change_ }}

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [ ] All values are in `rem`
- [ ] Text elements follow the truncation rules
- [ ] hover state of the element follow design spec
- [ ] focus state of the element follow design spec
- [ ] active state of the element follow design spec
- [ ] selected state of the element follow design spec
- [ ] selected hover state of the element follow design spec
- [ ] pressed state of the element follow design spec
- [ ] Responsiveness rules - the component has modifier classes for all breakpoints
- [ ] Includes Compact/Cosy/Tablet design
- [ ] RTL support
2. The code follows fundamental-styles code standards and style
- [ ] only one top level `fd-*` class is used in the file
- [ ] BEM naming convention is used
- [ ] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [ ] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [ ] `fd-reset()` mixin is applied to all elements
- [ ] Variables are used, if some value is used more than twice.
- [ ] Checked if current components can be reused, instead of having new code.
3. Testing
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] Updated tests
4. Documentation
- [ ] Storybook documentation has been created/updated
- [ ] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-01-18 00:27 UTC, InnaAtanasova requested changes
Please add an example commit string + a checkbox in the PR template (with example) so new contributors are not confused

2021-01-19 13:04 UTC, JKMarkowski approved these changes

2021-01-21 03:41 UTC, droshev commented
> Please add an example commit string + a checkbox in the PR template (with example) so new contributors are not confused

done

2021-01-22 14:38 UTC, InnaAtanasova approved these changes

2021-01-22 14:41 UTC, InnaAtanasova commented
> > Please add an example commit string + a checkbox in the PR template (with example) so new contributors are not confused
> 
> done

I would add an example commit message in the template. I am sure many people will have questions from the sort of "can I add more text to `[ci visual]`?", "Should the message start with `[ci visual]`?", etc.

2021-01-24 15:19 UTC, merged