docs: update buttons in compact bars
SAP/fundamental-styles pull request #2064
Opened 2021-01-16 16:45 UTC by droshev

## Related Issue
fixes: #2030

BREAKING CHANGE:
use compact buttons in compact bars

## Description
use compact buttons in compact bars

## Screenshots

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [ ] All values are in `rem`
- [ ] Text elements follow the truncation rules
- [ ] hover state of the element follow design spec
- [ ] focus state of the element follow design spec
- [ ] active state of the element follow design spec
- [ ] selected state of the element follow design spec
- [ ] selected hover state of the element follow design spec
- [ ] pressed state of the element follow design spec
- [ ] Responsiveness rules - the component has modifier classes for all breakpoints
- [ ] Includes Compact/Cosy/Tablet design
- [ ] RTL support
2. The code follows fundamental-styles code standards and style
- [ ] only one top level `fd-*` class is used in the file
- [ ] BEM naming convention is used
- [ ] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [ ] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [ ] `fd-reset()` mixin is applied to all elements
- [ ] Variables are used, if some value is used more than twice.
- [ ] Checked if current components can be reused, instead of having new code.
3. Testing
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] Updated tests
4. Documentation
- [ ] Storybook documentation has been created/updated
- [ ] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-01-18 00:32 UTC, InnaAtanasova requested changes
This is NOT a Breaking change, it's just an example of what can go inside a Bar component. The implementation libraries do not depend on this additional class. Also, the buttons were left cosy intentionally as the user is not prevented from mixing cozy/compact mode inside Bar component. For me personally this PR (the issue) does not bring value but if we decide to merge it, it should not be a Breaking change PR.

2021-01-18 21:13 UTC, droshev commented
> This is NOT a Breaking change, it's just an example of what can go inside a Bar component. The implementation libraries do not depend on this additional class. Also, the buttons were left cosy intentionally as the user is not prevented from mixing cozy/compact mode inside Bar component. For me personally this PR (the issue) does not bring value but if we decide to merge it, it should not be a Breaking change PR.

I agree with you. On the other hand we should show the best practices and the right approach.

2021-01-19 13:05 UTC, JKMarkowski approved these changes

2021-01-19 14:23 UTC, InnaAtanasova approved these changes

2021-01-21 03:32 UTC, droshev commented
> This is NOT a Breaking change, it's just an example of what can go inside a Bar component. The implementation libraries do not depend on this additional class. Also, the buttons were left cosy intentionally as the user is not prevented from mixing cozy/compact mode inside Bar component. For me personally this PR (the issue) does not bring value but if we decide to merge it, it should not be a Breaking change PR.

@InnaAtanasova I have updated one of the examples explaining that the we can mix compact bar with cozy elements. Thank you for pointing out.

2021-01-21 03:42 UTC, merged