[WIP]feat: introduce status indicator component
SAP/fundamental-styles pull request #2072
Opened 2021-01-21 16:59 UTC by Lokanathan-k

introduce status indicator component

## Related Issue
https://github.com/SAP/fundamental-styles/issues/2021

## Description
 Introduce status indicator component styles 

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [x] Text elements follow the truncation rules
- [x] hover state of the element follow design spec
- [x] focus state of the element follow design spec
- [x] active state of the element follow design spec
- [x] selected state of the element follow design spec
- [x] selected hover state of the element follow design spec
- [x] pressed state of the element follow design spec
- [x] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [x] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [x] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [x] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [x] tested Storybook examples with "CSS Resources" `normalize` option 
- [x] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [x] Verified all styles in IE11
- [x] Updated tests
4. Documentation
- [x] Storybook documentation has been created/updated
- [x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-01-22 06:47 UTC, kavya-b commented on stories/status-indicator/status-indicator.stories.js
> +<span style="min-width: 150px;">Critical Filling :</span>
inline styling is not encouraged. Can you place documentation related custom styling in custom.scss?

2021-01-22 06:56 UTC, kavya-b commented on src/status-indicator.scss
> +  &-htext {
this should probably be a modifier

2021-01-22 07:21 UTC, kavya-b commented
all examples not showing correct dotted focus: 
![image](https://user-images.githubusercontent.com/53509521/105458017-ce968280-5cad-11eb-88e1-f8127555d698.png)
![image](https://user-images.githubusercontent.com/53509521/105458187-15847800-5cae-11eb-90a9-9e7dd77121b6.png)

same titles for examples? 
![image](https://user-images.githubusercontent.com/53509521/105458425-8c217580-5cae-11eb-9bc0-0daf4859b926.png)

quartz dark doesn't work right in IE, could you check?
![image](https://user-images.githubusercontent.com/53509521/105459559-72812d80-5cb0-11eb-8c4b-70aa77e07594.png)

2021-01-25 08:29 UTC, sKudum commented
Hi lok,

**Query**.
 Are we targeting to provide svgs to users? as per my understanding application's UX team will create it and user has to tag them in html code and apply our modifier classes.

**Few observations.**
1).Having examples for Cirulcar fill, filling sequence, grouping, thresholds will help users.
2).How about radial and angular mechanisms, could not find any.
3).Sharing few details about usage will help, for example how can achieve required stroke, which class will help me to achieve radial mechanism, how I need to use it.
4). How I have to use these classes when I have a svg image shared from ux team?
           Try to use sketch for having one svg stored. in local, point out how a svg file and apply the classes for desired mechanisum.

_As mentioned before, we can take help of fiori-moments. how those guys are doing it._

2021-01-29 15:06 UTC, sKudum commented
Few Quires:

1). On click , on hover, active etc these svgs shouldn't have a11y features?
2).Are we targeting to give classes which help users to apply desired color and size in svg.  Everthing else its has to take help from svg?
3).Is it possible to have documentation with more details.
            we can state which options are from lib and from svg to obtain desired behaviour.?

2021-02-01 05:23 UTC, Lokanathan-k commented
> On click , on hover, active etc these svgs shouldn't have a11y features?

@puru-hk i have added the a11y feature as part of the pr, pls review this if it needs more details on the a11y for the above component.

2021-02-01 16:42 UTC, Lokanathan-k commented
> Few Quires:
> 
> 1). On click , on hover, active etc these svgs shouldn't have a11y features?
these on hover or active etc are not defined in the spec.
> 2).Are we targeting to give classes which help users to apply desired color and size in svg. Everthing else its has to take help from svg?
yes, we can only achieve the size and color other filling is done by lineargradient and radialgradient.
> 3).Is it possible to have documentation with more details.
added
> we can state which options are from lib and from svg to obtain desired behaviour.?

2021-02-02 04:32 UTC, DeepakSap14 approved these changes

2021-02-02 08:30 UTC, sKudum approved these changes
Approving it to avoid blocking, expecting queries be addressed with respected person consultation.

2021-02-02 09:09 UTC, puru-hk commented
Tested: From accessibility point of view able access view keyboard, tooltip is implemented for icon. 
But regarding the screen reader it is not reading the image icon.

2021-02-02 09:55 UTC, olshansky approved these changes

2021-02-02 12:04 UTC, JKMarkowski requested changes
Hello @Lokanathan-k 
Could you add commit with `[ci visual]` to trigger chromatic? After it I can approve - Good Job!

2021-02-03 05:03 UTC, puru-hk commented
Looks fine for me

2021-02-03 05:07 UTC, puru-hk approved these changes

2021-02-03 11:17 UTC, JKMarkowski approved these changes

2021-02-03 11:18 UTC, merged