fix: add truncation for List group header text
SAP/fundamental-styles pull request #2101
Opened 2021-01-29 16:43 UTC by InnaAtanasova

## Related Issue
Part of SAP/fundamental-styles#2063

## Description
This PR adds truncation rules for the List component Group Header <li> element

BREAKING CHANGE:
change in the markup, now the text is wrapped in a span with `fd-list__title` class.

Before:
```
<li role="listitem" class="fd-list__group-header">
    Group header 1
</li>
```
Now:
```
<li role="listitem" class="fd-list__group-header">
    <span class="fd-list__title">Group header 1</span>
 </li>
```

## Screenshots

### Before:
<img width="1188" alt="Screen Shot 2021-01-29 at 11 39 19 AM" src="https://user-images.githubusercontent.com/39598672/106302243-b501b780-6226-11eb-9844-c6c4c17f5de7.png">

### After:
<img width="1196" alt="Screen Shot 2021-01-29 at 11 39 37 AM" src="https://user-images.githubusercontent.com/39598672/106302259-b8953e80-6226-11eb-9d54-08e2cb953896.png">

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [x] Text elements follow the truncation rules
- [na] hover state of the element follow design spec
- [na] focus state of the element follow design spec
- [na] active state of the element follow design spec
- [na] selected state of the element follow design spec
- [na] selected hover state of the element follow design spec
- [na] pressed state of the element follow design spec
- [na] Responsiveness rules - the component has modifier classes for all breakpoints
- [na] Includes Compact/Cosy/Tablet design
- [na] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [na] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [na] `fd-reset()` mixin is applied to all elements
- [na] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [x] tested Storybook examples with "CSS Resources" `normalize` option 
- [x] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [x] Verified all styles in IE11
- [x] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [x] Storybook documentation has been created/updated
- [x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-02-02 13:33 UTC, JKMarkowski approved these changes

2021-02-02 13:37 UTC, JKMarkowski requested changes
Hi @InnaAtanasova  Could you apply these changes in every occurence of `fd-list__group-header`? I see it's missing in select/combobox/multi input (This is the moment when chromatic is useful)

2021-02-02 14:44 UTC, InnaAtanasova commented
> Hi @InnaAtanasova Could you apply these changes in every occurence of `fd-list__group-header`? I see it's missing in select/combobox/multi input (This is the moment when chromatic is useful)

Updated

2021-02-04 10:53 UTC, JKMarkowski approved these changes
LGTM

2021-02-04 14:05 UTC, merged