fix: grid list styles
SAP/fundamental-styles pull request #2115
Opened 2021-02-02 13:57 UTC by Betrozov

## Related Issue
Closes https://github.com/SAP/fundamental-ngx/issues/4560

## Description
Fixed label focus style and overflow

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [X] All values are in `rem`
- [X] Text elements follow the truncation rules
- [X] hover state of the element follow design spec
- [X] focus state of the element follow design spec
- [X] active state of the element follow design spec
- [X] selected state of the element follow design spec
- [X] selected hover state of the element follow design spec
- [X] pressed state of the element follow design spec
- [X] Responsiveness rules - the component has modifier classes for all breakpoints
- [X] Includes Compact/Cosy/Tablet design
- [X] RTL support
2. The code follows fundamental-styles code standards and style
- [X] only one top level `fd-*` class is used in the file
- [X] BEM naming convention is used
- [X] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [X] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [X] `fd-reset()` mixin is applied to all elements
- [X] Variables are used, if some value is used more than twice.
- [X] Checked if current components can be reused, instead of having new code.
3. Testing
- [X] tested Storybook examples with "CSS Resources" `normalize` option 
- [X] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [X] Verified all styles in IE11
- [X] Updated tests
- [X] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [X] Storybook documentation has been created/updated
- [X] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-02-02 14:34 UTC, IlyaSurmay approved these changes

2021-02-02 14:47 UTC, InnaAtanasova approved these changes

2021-02-02 14:47 UTC, InnaAtanasova commented
You need a commit message containing `[ci visual]` to trigger Chromatic

2021-02-04 12:09 UTC, JKMarkowski reviewed
Hello @Betrozov I think there is a lot of unnecessary code, check my suggestion - `input[type=radio]` element is never visible

2021-02-04 12:09 UTC, JKMarkowski commented on src/list-grid.scss
> +
```suggestion
      + .#{$block}__radio-label {
        @include fd-fiori-focus(0);
```

2021-02-04 12:10 UTC, JKMarkowski requested changes
Check my comment above

2021-02-04 14:21 UTC, JKMarkowski commented on src/list-grid.scss
> +        @include fd-fiori-focus(0);
So this can be removed

2021-02-04 15:33 UTC, JKMarkowski approved these changes

2021-02-09 13:25 UTC, Seamoo13 approved these changes

2021-02-09 13:52 UTC, merged