Fix Tabs component: underlying HTML [ci visual]
SAP/fundamental-styles pull request #2193
Opened 2021-03-10 18:45 UTC by itmilos

## Related Issue
Closes SAP/fundamental-styles#105

## Description
Changed anchor tags to button tags

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
> N/A 
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [na] All values are in `rem`
- [na] Text elements follow the truncation rules
- [na] hover state of the element follow design spec
- [na ] focus state of the element follow design spec
- [na] active state of the element follow design spec
- [na] selected state of the element follow design spec
- [na] selected hover state of the element follow design spec
- [na] pressed state of the element follow design spec
- [na] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [na] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [na] BEM naming convention is used
- [na] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [na] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [na] `fd-reset()` mixin is applied to all elements
- [na] Variables are used, if some value is used more than twice.
- [na] Checked if current components can be reused, instead of having new code.
3. Testing
- [na] tested Storybook examples with "CSS Resources" `normalize` option 
- [na] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [na] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [ ] Storybook documentation has been created/updated
- [na] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-03-10 18:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/fundamental-styles?pullRequest=2193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/fundamental-styles?pullRequest=2193) before we can accept your contribution.<br/><hr/>**Milos Rujevic (mikeRujevic)** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/fundamental-styles?pullRequest=2193) it.</sub>

2021-03-10 21:42 UTC, droshev requested changes
You need to update the tests.
Can you mark and document this as a breaking change?
Also, can you check in other places if the tabs are used and update the markup?

2021-03-11 11:06 UTC, itmilos commented
I added **role="presentation"** to **li** element and **role="tab"** to **button** ref. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_presentation_role

2021-03-11 19:46 UTC, itmilos commented
> I added **role="presentation"** to **li** element and **role="tab"** to **button** ref. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_presentation_role

This approach does not meet the accessibility tests standard

2021-03-11 19:52 UTC, itmilos commented
## 0.17.0

#### Tabs - change element  from `a` to `button`

Before:
```
 <li role="tab" class="fd-tabs__item">
                            <a class="fd-tabs__link">
                                <span class="fd-tabs__tag">
                                    Link
                                </span>
                            </a>
                        </li>
...
```

After:
```
 <li role="tab" class="fd-tabs__item">
                            <button class="fd-tabs__link">
                                <span class="fd-tabs__tag">
                                    Link
                                </span>                           
 </button>
                        </li>
...
```

2021-03-11 21:24 UTC, InnaAtanasova commented on stories/notification/notification.stories.js
> +            <button
Buttons are missing tabindex, also missing is the aria-selected

2021-03-11 21:26 UTC, InnaAtanasova requested changes
The examples are no longer changing the tab panels. 
To reproduce:
- click on a different Tab
- the tab panel content is not updated

2021-03-11 23:03 UTC, droshev commented
@itmilos you can move to branch PR

2021-03-12 06:52 UTC, closed without merging