fix: removal of extra margin on the labelled status indicator
SAP/fundamental-styles pull request #2367
Opened 2021-05-20 09:50 UTC by Lokanathan-k

## Related Issue
Closes: https://github.com/SAP/fundamental-styles/issues/2331

## Description
Removal of extra margin on the labelled status indicator

## Screenshots

### Before:
<img width="619" alt="116866104-76660980-ac28-11eb-8415-3606b75d2b1b" src="https://user-images.githubusercontent.com/53534379/118957158-e8a35180-b97d-11eb-85f2-45808cd1d305.png">

### After:

<img width="455" alt="Screenshot 2021-05-20 at 3 13 49 PM" src="https://user-images.githubusercontent.com/53534379/118957311-0a043d80-b97e-11eb-84ef-e1c255895d84.png">

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [N/A]  All values are in `rem`
- [N/A]  Text elements follow the truncation rules
- [N/A] hover state of the element follow design spec
- [N/A] focus state of the element follow design spec
- [N/A] active state of the element follow design spec
- [N/A] selected state of the element follow design spec
- [N/A] selected hover state of the element follow design spec
- [N/A] pressed state of the element follow design spec
- [N/A] Responsiveness rules - the component has modifier classes for all breakpoints
- [N/A] Includes Compact/Cosy/Tablet design
- [N/A] RTL support
2. The code follows fundamental-styles code standards and style
- [N/A] only one top level `fd-*` class is used in the file
- [N/A] BEM naming convention is used
- [N/A] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [N/A] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [N/A] `fd-reset()` mixin is applied to all elements
- [N/A] Variables are used, if some value is used more than twice.
- [N/A] Checked if current components can be reused, instead of having new code.
3. Testing
- [N/A] tested Storybook examples with "CSS Resources" `normalize` option 
- [N/A] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [N/A] Verified all styles in IE11
- [N/A] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [N/A] Storybook documentation has been created/updated
- [x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-05-20 11:18 UTC, DeepakSap14 approved these changes

2021-05-20 17:18 UTC, InnaAtanasova requested changes
You need to handle RTL support for `--right` and `--left`. For the label and for the indicator.
<img width="349" alt="Screen Shot 2021-05-20 at 1 15 56 PM" src="https://user-images.githubusercontent.com/39598672/119021661-b0941280-b96d-11eb-9967-909671ec3ece.png">
<img width="460" alt="Screen Shot 2021-05-20 at 1 15 43 PM" src="https://user-images.githubusercontent.com/39598672/119021664-b12ca900-b96d-11eb-82ad-14529dd3b215.png">
<img width="518" alt="Screen Shot 2021-05-20 at 1 15 23 PM" src="https://user-images.githubusercontent.com/39598672/119021665-b1c53f80-b96d-11eb-8daa-1ce83be59726.png">
<img width="214" alt="Screen Shot 2021-05-20 at 1 16 11 PM" src="https://user-images.githubusercontent.com/39598672/119021667-b1c53f80-b96d-11eb-9206-68fa5df4f463.png">

2021-05-21 21:59 UTC, InnaAtanasova approved these changes

2021-05-21 22:03 UTC, InnaAtanasova requested changes
I noticed the label does not have RTL, the indicator also is not changed in RTL
<img width="362" alt="Screen Shot 2021-05-21 at 6 01 45 PM" src="https://user-images.githubusercontent.com/39598672/119202431-c03f5400-ba5e-11eb-8636-d2106e488216.png">
<img width="384" alt="Screen Shot 2021-05-21 at 6 01 57 PM" src="https://user-images.githubusercontent.com/39598672/119202428-bfa6bd80-ba5e-11eb-8425-e8d1803ee3da.png">


<img width="346" alt="Screen Shot 2021-05-21 at 6 02 05 PM" src="https://user-images.githubusercontent.com/39598672/119202430-c03f5400-ba5e-11eb-90ba-d5911882ee06.png">
<img width="175" alt="Screen Shot 2021-05-21 at 6 01 33 PM" src="https://user-images.githubusercontent.com/39598672/119202433-c03f5400-ba5e-11eb-921b-c1fe186480d8.png">

2021-05-24 16:02 UTC, Lokanathan-k commented
> I noticed the label does not have RTL, the indicator also is not changed in RTL
> <img alt="Screen Shot 2021-05-21 at 6 01 45 PM" width="362" src="https://user-images.githubusercontent.com/39598672/119202431-c03f5400-ba5e-11eb-8636-d2106e488216.png">
> <img alt="Screen Shot 2021-05-21 at 6 01 57 PM" width="384" src="https://user-images.githubusercontent.com/39598672/119202428-bfa6bd80-ba5e-11eb-8425-e8d1803ee3da.png">
> 
> <img alt="Screen Shot 2021-05-21 at 6 02 05 PM" width="346" src="https://user-images.githubusercontent.com/39598672/119202430-c03f5400-ba5e-11eb-90ba-d5911882ee06.png">
> 
> <img alt="Screen Shot 2021-05-21 at 6 01 33 PM" width="175" src="https://user-images.githubusercontent.com/39598672/119202433-c03f5400-ba5e-11eb-921b-c1fe186480d8.png">

@InnaAtanasova this is just a span tag to define a type of indicator, not a label is used this label is not part of the component.

2021-05-25 17:54 UTC, InnaAtanasova commented
Ok, for the label. Maybe it was better to use fundamental label but it's ok to keep it like this. What about the other problem? In the specs the illustration is always centered in the "container". But in your case, for left and right, the illustration is not centered. 
Wiki specs:
<img width="345" alt="Screen Shot 2021-05-25 at 1 50 40 PM" src="https://user-images.githubusercontent.com/39598672/119545272-a3599800-bd60-11eb-805f-15e2dc8bd65c.png">

Your case:
<img width="375" alt="Screen Shot 2021-05-25 at 1 51 11 PM" src="https://user-images.githubusercontent.com/39598672/119545292-a785b580-bd60-11eb-980d-d6972900402c.png">
<img width="361" alt="Screen Shot 2021-05-25 at 1 51 04 PM" src="https://user-images.githubusercontent.com/39598672/119545294-a81e4c00-bd60-11eb-8082-b3338800182b.png">

2021-05-26 04:53 UTC, Lokanathan-k commented
> Ok, for the label. Maybe it was better to use fundamental label but it's ok to keep it like this. What about the other problem? In the specs the illustration is always centered in the "container". But in your case, for left and right, the illustration is not centered.
> Wiki specs:
> <img alt="Screen Shot 2021-05-25 at 1 50 40 PM" width="345" src="https://user-images.githubusercontent.com/39598672/119545272-a3599800-bd60-11eb-805f-15e2dc8bd65c.png">
> 
> Your case:
> <img alt="Screen Shot 2021-05-25 at 1 51 11 PM" width="375" src="https://user-images.githubusercontent.com/39598672/119545292-a785b580-bd60-11eb-980d-d6972900402c.png">
> <img alt="Screen Shot 2021-05-25 at 1 51 04 PM" width="361" src="https://user-images.githubusercontent.com/39598672/119545294-a81e4c00-bd60-11eb-8082-b3338800182b.png">

@InnaAtanasova Maybe it was better to use fundamental label but it's ok to keep it like this, _**will change this**_.

In the specs the illustration is always centered in the "container". But in your case, for left and right, the illustration is not centered.

for the exmple with right and left label if the image is aligned in center then the space between the svg and label will be more, Because the image position is defined viewbox property of the SVG ,and SAPui5 example was used to as a reference to achieve the same.

SapUI5 exmaple:
<img width="934" alt="Screenshot 2021-05-26 at 10 16 48 AM" src="https://user-images.githubusercontent.com/53534379/119604102-1f5cea00-be0c-11eb-8f9b-0c5912b8eb3d.png">

SVG without label are aligned to the centered to container.
![image](https://user-images.githubusercontent.com/53534379/119604288-6f3bb100-be0c-11eb-998b-77152f9f954c.png)

2021-05-26 15:16 UTC, InnaAtanasova approved these changes

2021-05-26 15:17 UTC, merged