fix: change tabs styles for routerLink
SAP/fundamental-styles pull request #2473
Opened 2021-06-22 12:25 UTC by OleksiyDrozdov

## Related Issue
[#5128](https://github.com/SAP/fundamental-ngx/issues/5128)

## Description
{{ _Enter short description of the change_ }}

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [x] Text elements follow the truncation rules
- [x] hover state of the element follow design spec
- [x] focus state of the element follow design spec
- [x] active state of the element follow design spec
- [x] selected state of the element follow design spec
- [x] selected hover state of the element follow design spec
- [x] pressed state of the element follow design spec
- [x] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [n/a] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [n/a] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [x] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [n/a] tested Storybook examples with "CSS Resources" `normalize` option 
- [n/a] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [n/a] Verified all styles in IE11
- [n/a] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [n/a] Storybook documentation has been created/updated
- [n/a] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-06-22 19:44 UTC, InnaAtanasova requested changes
You are missing the word `closes` or `fixes` in front of the PR number and description with before/after screenshots. You need to add reviewers, labels, project, etc.

2021-06-22 19:44 UTC, InnaAtanasova commented on src/tabs.scss
> +    &.is-selected {
You need to use `fd-selected()` mixin

2021-06-22 19:44 UTC, InnaAtanasova commented on src/tabs.scss
> +      .fd-tabs__icon {
.#{$block}__icon

2021-06-22 19:44 UTC, InnaAtanasova commented on src/tabs.scss
> +      .fd-tabs__tag::after {
.#{$block}__tag

2021-06-23 14:44 UTC, InnaAtanasova approved these changes

2021-06-25 19:55 UTC, InnaAtanasova commented
@OleksiyDrozdov UI tests are not triggered

2021-06-29 10:56 UTC, dimamarksman approved these changes

2021-06-30 19:07 UTC, merged