fix: added wrapper for slider [ci visual]
SAP/fundamental-styles pull request #2504
Opened 2021-06-29 06:52 UTC by Smiranin

## Related Issue
Closes SAP/fundamental-styles#2503

## Description
Added wrapper for slider to prevent getting out of the strip edges of slider track. (look related issue)
Also fixed position of "before element" of handle for rtl.

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:
![2021-06-29_09-50](https://user-images.githubusercontent.com/14183958/123750700-91b76300-d8bf-11eb-80eb-1d58aa8833d7.png)

### After:
![2021-06-29_09-51](https://user-images.githubusercontent.com/14183958/123750710-967c1700-d8bf-11eb-8af5-7d0e4455df7b.png)

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [ ] All values are in `rem`
- [ ] Text elements follow the truncation rules
- [ ] hover state of the element follow design spec
- [ ] focus state of the element follow design spec
- [ ] active state of the element follow design spec
- [ ] selected state of the element follow design spec
- [ ] selected hover state of the element follow design spec
- [ ] pressed state of the element follow design spec
- [ ] Responsiveness rules - the component has modifier classes for all breakpoints
- [ ] Includes Compact/Cosy/Tablet design
- [ ] RTL support
2. The code follows fundamental-styles code standards and style
- [ ] only one top level `fd-*` class is used in the file
- [ ] BEM naming convention is used
- [ ] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [ ] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [ ] `fd-reset()` mixin is applied to all elements
- [ ] Variables are used, if some value is used more than twice.
- [ ] Checked if current components can be reused, instead of having new code.
3. Testing
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] Updated tests
- [ ] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [ ] Storybook documentation has been created/updated
- [ ] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-06-29 14:03 UTC, InnaAtanasova requested changes

2021-06-29 14:40 UTC, Smiranin commented on src/slider.scss
> +.#{$block}-wrapper {
No, it is the parent element of the `.fd-slider`.

2021-06-30 07:42 UTC, Smiranin commented on src/slider.scss
> +  padding-right: 0.625rem;
Done

2021-06-30 07:42 UTC, Smiranin commented on src/slider.scss
> +    padding-right: 0.8125rem;
+

2021-06-30 07:42 UTC, Smiranin commented on src/slider.scss
> +[dir='rtl'] {
+

2021-06-30 07:43 UTC, Smiranin commented on src/slider.scss
> +.#{$block}-wrapper {
Updated changes. Remove all changes from html and removed wrapper. Added styles for fd-slider class

2021-07-02 16:52 UTC, InnaAtanasova commented on src/slider.scss
> +  &--lg-x-paddings {
Please rename it to just `&--lg`. You can add in the documentation (the text above the example for mobile mode something like:
"To add horizontal paddings of 0.625rem use the <code>fd-slider--lg</code> modifier class".

2021-07-05 17:37 UTC, InnaAtanasova approved these changes

2021-07-06 07:09 UTC, N1XUS approved these changes

2021-07-06 12:26 UTC, dimamarksman approved these changes

2021-07-06 13:09 UTC, merged