[WIP] fix: layout grid bug fixes, improvements, refactoring
SAP/fundamental-styles pull request #2717
Opened 2021-09-06 09:31 UTC by platon-rov

[WIP] Until approved visual tests.

## Related Issue

Closes #2612.

## Description

Negative margins were applied to the inappropriate elements that make rows wider than container and cause appearing the scrollbars. 

Gutter between rows was set by padding for the column not by a margin for the row.

## Screenshots

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [X] All values are in `rem`
- [X] Text elements follow the truncation rules
- [X] hover state of the element follow design spec
- [X] focus state of the element follow design spec
- [X] active state of the element follow design spec
- [X] selected state of the element follow design spec
- [X] selected hover state of the element follow design spec
- [X] pressed state of the element follow design spec
- [X] Responsiveness rules - the component has modifier classes for all breakpoints
- [X] Includes Compact/Cosy/Tablet design
- [X] RTL support
2. The code follows fundamental-styles code standards and style
- [X] only one top level `fd-*` class is used in the file
- [X] BEM naming convention is used
- [X] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [X] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [X] `fd-reset()` mixin is applied to all elements
- [X] Variables are used, if some value is used more than twice.
- [X] Checked if current components can be reused, instead of having new code.
3. Testing
- [X] tested Storybook examples with "CSS Resources" `normalize` option 
- [X] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [X] Verified all styles in IE11
- [ ] Updated tests
- [X] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [X] Storybook documentation has been created/updated
- [X] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2021-09-08 16:29 UTC, InnaAtanasova commented
@platon-rov please add `before` and `after` screenshots of a component affected by the changes.

2021-09-08 16:47 UTC, InnaAtanasova requested changes

2021-09-08 16:47 UTC, InnaAtanasova commented on src/layout-grid.scss
> +      margin-right: 0;
There's a mixin for resetting the horizontal margin:
```
@mixin fd-reset-margins-x() {
  margin-left: 0;
  margin-right: 0;
}
```

2021-09-08 16:47 UTC, InnaAtanasova commented on src/layout-grid.scss
> +        padding-right: 0;
Please use the mixin:
```
@mixin fd-reset-paddings-x() {
  padding-left: 0;
  padding-right: 0;
}
```

2021-09-08 16:47 UTC, InnaAtanasova commented on src/layout-grid.scss
> +    padding-top: 0.5rem;
could you please put values like `0.5rem`, `0.25rem`, etc. in variables. This way we can easily change and maintain them.

2021-09-10 17:34 UTC, InnaAtanasova approved these changes

2021-09-13 07:15 UTC, Smiranin approved these changes

2021-09-13 15:18 UTC, merged