feat(styles): focus outline is visible now [ci visual]
SAP/fundamental-styles pull request #3123
Opened 2022-01-26 20:56 UTC by g-cheishvili

## Related Issue
Part of SAP/fundamental-ngx#7587

## Description
Focus outline was not visible on tab headers in case of icon tabs. This was because offset was negative exactly same as width of outline. I removed negativity and now it is visible

## Screenshots

### Before:
![before](https://user-images.githubusercontent.com/28543391/151245499-021ef1ea-55d1-4aa9-be5e-66bb9f20ba2d.png)

### After:
![after](https://user-images.githubusercontent.com/28543391/151245523-8227a153-0135-405c-8359-09effc50c9f3.png)

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [ ] All values are in `rem`
- [ ] Text elements follow the truncation rules
- [ ] hover state of the element follow design spec
- [ ] focus state of the element follow design spec
- [ ] active state of the element follow design spec
- [ ] selected state of the element follow design spec
- [ ] selected hover state of the element follow design spec
- [ ] pressed state of the element follow design spec
- [ ] Responsiveness rules - the component has modifier classes for all breakpoints
- [ ] Includes Compact/Cosy/Tablet design
- [ ] RTL support
2. The code follows fundamental-styles code standards and style
- [ ] only one top level `fd-*` class is used in the file
- [ ] BEM naming convention is used
- [ ] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [ ] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [ ] `fd-reset()` mixin is applied to all elements
- [ ] Variables are used, if some value is used more than twice.
- [ ] Checked if current components can be reused, instead of having new code.
3. Testing
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] Updated tests
- [ ] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [ ] Storybook documentation has been created/updated
- [ ] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2022-01-27 13:35 UTC, platon-rov reviewed
It looks got however I didn't find any information about how it should looks in wiki. 

In sapui5 it's totally different, [example](https://sapui5.hana.ondemand.com/#/entity/sap.m.IconTabBar/sample/sap.m.sample.IconTabBarMulti)

In icon tab bar component it's also a bit different, [example](https://fundamental-ngx.netlify.app/#/platform/icon-tab-bar#icon-type).

I would say let's make it's the same as in the icon tab bar component and send an email to confirm how exactly it should looks like.

2022-01-27 20:14 UTC, InnaAtanasova requested changes
I sent you and @platon-rov link to the visual specs for the focus

2022-01-28 10:33 UTC, g-cheishvili commented
> It looks got however I didn't find any information about how it should looks in wiki.
> 
> In sapui5 it's totally different, [example](https://sapui5.hana.ondemand.com/#/entity/sap.m.IconTabBar/sample/sap.m.sample.IconTabBarMulti)
> 
> In icon tab bar component it's also a bit different, [example](https://fundamental-ngx.netlify.app/#/platform/icon-tab-bar#icon-type).
> 
> I would say let's make it's the same as in the icon tab bar component and send an email to confirm how exactly it should looks like.

I made it look like sapui5 one

2022-01-28 18:09 UTC, InnaAtanasova approved these changes

2022-01-29 13:56 UTC, merged