fix: fixed card layout refactoring
SAP/fundamental-styles pull request #3208
Opened 2022-02-25 08:10 UTC by platon-rov

## Related Issue

Related issue https://github.com/SAP/fundamental-ngx/pull/7701

## Description

Fixed card layout component refactoring because of changes on the ngx side.

## Screenshots

No visual changes.

## Breaking changes:

* No more fixed card layout columns
* Container element should have column class
* Container element should have height\max-height
* Wrapper element for card introduced

2022-03-01 17:13 UTC, mikerodonnell89 requested changes
There is some confusing wording in the docs about adding a wrapper element but there is a separate class called wrapper so I made a suggestion to clarify the docs a bit. However looking at the template, I am wondering why we need two separate classes, `fd-fixed-card-layout__wrapper` and `fd-fixed-card-layout__card`. I am not seeing any element other than the card within the wrapper so can all the styles for wrapper simply be applied to card and we no longer need the wrapper element/class?

2022-03-01 18:09 UTC, InnaAtanasova commented on src/styles/fixed-card-layout.scss
> +    justify-content: flex-start;
On line 15 the `fd-flex-horizontal-center` mixin is imported. This mixin brings:
```
@mixin fd-flex-horizontal-center {
  display: flex;
  justify-content: center;
  @content;
}
```
so you don't need line 18 and you need to put the additional flex related code in the mixin body:
```
@include fd-flex-horizontal-center() {
    flex-wrap: wrap;
    flex-direction: column;
    justify-content: flex-start;
}
```

2022-03-03 14:24 UTC, platon-rov commented on stories/fixed-card-layout/fixed-card-layout.stories.js
> +* Wrap each card in element with class \`fd-fixed-card-layout__wrapper\` and apply \`fd-fixed-card-layout__card\` class to the card element.`
Agree with you, previous couldn't get it, finally i found the way.

2022-03-03 20:30 UTC, InnaAtanasova approved these changes

2022-03-07 17:07 UTC, mikerodonnell89 approved these changes

2022-03-09 12:57 UTC, merged