fix: upload collection overflow [ci visual]
SAP/fundamental-styles pull request #3227
Opened 2022-03-09 11:33 UTC by platon-rov

## Related Issue

Part of https://github.com/SAP/fundamental-ngx/issues/7815

## Description

Overflow handling improvements.
Modifier classes added to the upload collection item object status to handle overflow approriate.

## Screenshots

### Before:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/20265336/157433652-753865b7-de32-47bd-9b39-f1254457c692.png">

### After:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/20265336/157433847-97dd9d57-d054-4c88-ba4e-16e5264d4686.png">

## BREAKING CHANGE:
* upload collection item object status now needs additional classes to be applied

2022-03-10 19:43 UTC, InnaAtanasova requested changes
This is a Breaking Change. Please document it in the Wiki and in the PR description

2022-03-12 13:00 UTC, platon-rov commented
> This is a Breaking Change. Please document it in the Wiki and in the PR description

Done. https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#upload-collection-3227

2022-03-14 22:11 UTC, g-cheishvili requested changes
GG. Just take care of those massacred characters

2022-03-14 22:11 UTC, g-cheishvili commented on src/styles/upload-collection.scss
> +        @include fd-ellipsis();
```suggestion
        @include fd-ellipsis();
        line-height: initial;
```
This should fix that cut-down characters

2022-03-21 19:00 UTC, aberikashvili approved these changes
LGTM

2022-03-22 09:26 UTC, g-cheishvili commented
For some reason action buttons are vertically aligned in case of long texts, but horizontally when short texts. Is that how it should be? @platon-rov

2022-03-23 16:41 UTC, g-cheishvili approved these changes

2022-03-23 17:28 UTC, merged