fix(chore): wizard various fixes
SAP/fundamental-styles pull request #3425
Opened 2022-05-14 09:34 UTC by platon-rov

## Related Issue

Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1122057340

## Description

Wizard various fixes.

## Screenshots

### Before:

* Horizon
<img width="139" alt="Screenshot 2022-05-08 at 16 36 19" src="https://user-images.githubusercontent.com/20265336/167298755-5030c01f-182a-4fd5-9eff-30e622b26a5c.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/20265336/167298917-e385a0fe-7302-4b93-93b3-8174b1c0fdb9.png">

* Fiori
<img width="179" alt="image" src="https://user-images.githubusercontent.com/20265336/167299342-d664f43e-db0e-4788-8d03-06b0a0c70227.png">

### After:

* Horizon
<img width="908" alt="image" src="https://user-images.githubusercontent.com/20265336/168420023-8ce81f25-3533-4551-bdd1-48393f1b1dd2.png">
<img width="317" alt="image" src="https://user-images.githubusercontent.com/20265336/168420079-032ed7bb-df44-4842-839e-268b11d79d1b.png">

* Fiori
<img width="917" alt="image" src="https://user-images.githubusercontent.com/20265336/168420094-f4aad494-8c76-42d6-9984-f2c3f6e5118b.png">

2022-05-17 20:56 UTC, mikerodonnell89 requested changes
Looking at the specs for horizon, the current step label is explicitly stated to be `--sapContent_Selected_ForegroundColor `. It looks like in a few screenshots they have accidentally left the text black but in most examples and explicitly mentioned under the "wizard tab states" section B, the label text color is `--sapContent_Selected_ForegroundColor`

2022-05-18 12:53 UTC, platon-rov commented
> Looking at the specs for horizon, the current step label is explicitly stated to be `--sapContent_Selected_ForegroundColor `. It looks like in a few screenshots they have accidentally left the text black but in most examples and explicitly mentioned under the "wizard tab states" section B, the label text color is `--sapContent_Selected_ForegroundColor`

Looks reasonable. Changed.

2022-05-19 18:53 UTC, mikerodonnell89 approved these changes

2022-05-20 11:05 UTC, g-cheishvili approved these changes

2022-05-23 06:01 UTC, merged