fix(styles): fix the button states in expanded Select [ci visual]
SAP/fundamental-styles pull request #3438
Opened 2022-05-17 19:24 UTC by InnaAtanasova

## Related Issue
Closes SAP/fundamental-styles#](https://github.com/SAP/fundamental-styles/issues/3434)

## Description
This PR fixes the button in Select control when it's in expanded state. The fix automatically solves the issue in Pagination as it uses Select. 

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).

### Before:
<img width="665" alt="Screen Shot 2022-05-17 at 3 21 22 PM" src="https://user-images.githubusercontent.com/39598672/168893528-3b44e85f-dc3b-4983-8b63-f3c1e1bb5e68.png">
<img width="147" alt="Screen Shot 2022-05-17 at 3 21 40 PM" src="https://user-images.githubusercontent.com/39598672/168893531-08e2cbba-df89-42d2-bc6e-231e9235c417.png">
<img width="171" alt="Screen Shot 2022-05-17 at 3 20 49 PM" src="https://user-images.githubusercontent.com/39598672/168893533-5487f756-da95-46e1-b8e5-214f0b5584fa.png">

### After:
<img width="657" alt="Screen Shot 2022-05-17 at 3 20 00 PM" src="https://user-images.githubusercontent.com/39598672/168893674-2d707020-1f2c-4194-9e7f-cce36abd0d34.png">

<img width="649" alt="Screen Shot 2022-05-17 at 3 19 50 PM" src="https://user-images.githubusercontent.com/39598672/168893142-80a4187e-48f2-4a44-a39d-52f68ce16183.png">
<img width="170" alt="Screen Shot 2022-05-17 at 3 19 21 PM" src="https://user-images.githubusercontent.com/39598672/168893143-bcc7ba65-3bfd-4c76-87e0-c671232eb3b6.png">
<img width="159" alt="Screen Shot 2022-05-17 at 3 19 05 PM" src="https://user-images.githubusercontent.com/39598672/168893145-1231148d-4403-4a60-a7ea-e443084aa42d.png">

2022-05-17 21:37 UTC, mikerodonnell89 commented on src/styles/mixins/_forms.scss
> +    @include fd-set-border-left(var(--sapButton_BorderWidth) solid transparent);
What is the point of this anyways? The icon looks just slightly out-of-center in the button and I think this may be the culprit

2022-05-18 11:05 UTC, N1XUS approved these changes

2022-05-19 10:32 UTC, platon-rov approved these changes

2022-05-20 10:54 UTC, g-cheishvili requested changes
We could use CSS variable scopes to reduce size. It will not break anything, just will improve

2022-05-20 10:54 UTC, g-cheishvili commented on src/styles/select.scss
> +@mixin fd-select-button-settings($bkgdColor, $borderLeft) {
We should use dash-case in scss variables

2022-05-23 17:54 UTC, mikerodonnell89 commented on src/styles/mixins/_forms.scss
> +    @include fd-set-border-left(var(--sapButton_BorderWidth) solid transparent);
So I think we can have a border width of 0 for non-HC modes

2022-05-24 14:46 UTC, merged