fix(styles): remove product switch control class [ci visual]
SAP/fundamental-styles pull request #3442
Opened 2022-05-18 17:07 UTC by mikerodonnell89

Part of https://github.com/SAP/fundamental-ngx/issues/7984

Removes an old class that is no longer required because the styles are covered by `fd-button--transparent` class.

2022-05-19 10:23 UTC, platon-rov reviewed
Isn't it a breaking change? As we don't need to apply this class anymore.

2022-05-19 16:02 UTC, mikerodonnell89 commented
> 3\. Maybe use the code for `fd-shellbar__button` class by moving it to a mixin or placeholder and reuse it for Product Switch:

Product switch doesn't need this anymore if all the styles are coming from button and fd-shellbar__button

2022-05-20 18:54 UTC, InnaAtanasova requested changes

2022-05-20 18:54 UTC, InnaAtanasova commented on stories/product-switch/product-switch.stories.js
> +                <button class="fd-button fd-button--transparent fd-popover__control"
You have a div on line 36 with `fd-popover__control` class and the same class applied on the button. Maybe remove the parent div.

2022-05-20 18:54 UTC, InnaAtanasova commented on stories/shellbar/shellbar.stories.js
> +                                class="fd-button fd-button--transparent fd-shellbar__button fd-popover__control"
same as above

2022-05-26 13:26 UTC, InnaAtanasova requested changes
<img width="826" alt="Screen Shot 2022-05-26 at 9 25 05 AM" src="https://user-images.githubusercontent.com/39598672/170496695-8e1af1b7-7b8e-450f-b11c-e5a086259cc8.png">


The example in Product Switch should be updated. We either use ShellBar in this example or remove it from there, o.w. users can report it as a bug.

2022-05-28 00:50 UTC, mikerodonnell89 commented
> <img alt="Screen Shot 2022-05-26 at 9 25 05 AM" width="826" src="https://user-images.githubusercontent.com/39598672/170496695-8e1af1b7-7b8e-450f-b11c-e5a086259cc8.png">
> 
> The example in Product Switch should be updated. We either use ShellBar in this example or remove it from there, o.w. users can report it as a bug.

Thanks! updated to use shellbar

2022-06-01 15:33 UTC, InnaAtanasova approved these changes

2022-06-02 15:28 UTC, merged