fix(styles): tile horizon interaction states
SAP/fundamental-styles pull request #3474
Opened 2022-05-23 21:52 UTC by g-cheishvili

## Related Issue
Part of #3327 

## Description
fixed tile interaction state diffs

2022-05-24 21:07 UTC, mikerodonnell89 commented on src/styles/theming/common/tile/_sap_horizon_hc.scss
> +  --fdTile_Hover_Box_Shadow: 0 0 0 0.125rem var(--sapTile_BorderColor); // this will add missing 0.125rem to the border to fill required .1875rem
cool workaround

2022-05-24 21:10 UTC, mikerodonnell89 requested changes
This looks good. Should we move the repeated `/* Generic Tile */` styles from `src/styles/theming/sap_fiori_3.scss`, `src/styles/theming/sap_fiori_3_dark.scss`, etc. into the new scss files in `src/styles/theming/common/tile` ?

2022-05-24 21:19 UTC, g-cheishvili commented on src/styles/theming/common/tile/_sap_horizon_hc.scss
> +  --fdTile_Hover_Box_Shadow: 0 0 0 0.125rem var(--sapTile_BorderColor); // this will add missing 0.125rem to the border to fill required .1875rem
Yeah, otherwise content would jump on hover :(

2022-05-26 13:42 UTC, InnaAtanasova approved these changes

2022-05-27 00:22 UTC, merged