fix(styles): flexible column layout background
SAP/fundamental-styles pull request #3546
Opened 2022-06-07 13:54 UTC by platon-rov

## Related Issue

Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1128609647

## Description

Flexible Column Layout background to support various themes.

## Screenshots

### Before:
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/20265336/172398183-bb49e896-e6a4-4411-9136-2242a7d77453.png">

### After:

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/20265336/172397752-aabc27bf-59a2-4685-abd0-90d74e7b7ce8.png">

2022-06-07 15:22 UTC, mikerodonnell89 requested changes
Do we want to be adding the background to the component itself, or rather just the documentation? I think the latter

2022-06-10 15:43 UTC, mikerodonnell89 approved these changes

2022-06-10 17:37 UTC, InnaAtanasova approved these changes

2022-06-10 17:38 UTC, InnaAtanasova commented
I renamed the PR to docs as it's not fixing the code, but rather the documentation.

2022-06-12 13:02 UTC, merged