fix(styles): padding issues and RTL placeholder issues
SAP/fundamental-styles pull request #3744
Opened 2022-07-20 20:15 UTC by mikerodonnell89

fixes #3742 

Italicized, right-aligned text is cut off by neighboring elements so this adds a small indent to the placeholder text in RTL mode.  This PR also corrects a minor RTL padding bug for input group

before:
![image](https://user-images.githubusercontent.com/2471874/180073165-4e26b10b-632e-43c8-8321-95715c287ee0.png)

after:
<img width="147" alt="Screen Shot 2022-07-20 at 4 04 16 PM" src="https://user-images.githubusercontent.com/2471874/180073180-9f625693-5c60-4bc0-9fa7-72709e36c394.png">

2022-07-20 20:18 UTC, g-cheishvili approved these changes

2022-07-21 01:16 UTC, droshev requested changes
@mikerodonnell89 Can you trigger chromatic?

2022-07-21 09:58 UTC, platon-rov approved these changes

2022-07-21 13:54 UTC, droshev approved these changes

2022-07-21 14:07 UTC, merged