feat(styles): skeleton
SAP/fundamental-styles pull request #3766
Opened 2022-08-02 20:33 UTC by platon-rov

## Related Issue

Refers to https://github.com/SAP/fundamental-ngx/pull/8258
Refers to dxp/ngx-dxp/75

## Description

Skeleton styles & component.

## Screenshots

### After:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/20265336/182468126-7cc6bd6b-dcaf-4317-8b36-c805a49a726f.png">

2022-08-10 18:50 UTC, g-cheishvili approved these changes
Nice

2022-08-10 19:51 UTC, InnaAtanasova requested changes
Blocked as it needs some work after today's discusssion.

2022-08-16 22:18 UTC, mikerodonnell89 commented on stories/input-group/__snapshots__/input-group.stories.storyshot
>          class="fd-input fd-input-group__input"
accidental commit?

2022-08-30 16:11 UTC, mikerodonnell89 requested changes

2022-08-30 16:11 UTC, mikerodonnell89 commented on src/styles/skeleton.scss
> +  pointer-events: none !important;
`pointer-events: none` breaks `cursor: wait`

2022-09-23 13:57 UTC, InnaAtanasova commented on src/styles/skeleton.scss
> +    margin-bottom: 0.25rem !important;
Please use mixin `fd-set-margins-y-equal`

2022-09-23 13:57 UTC, InnaAtanasova commented on src/styles/skeleton.scss
> +      margin-bottom: 0 !important;
Please use mixin `fd-set-margins-y-equal`

2022-09-23 13:57 UTC, InnaAtanasova commented on src/styles/skeleton.scss
> +  @include fd-reset();
why do you need the reset?
I see cases like this: `fd-button fd-button--primary fd-skeleton`, which means that `fd-skeleton` can be/is a "modifier" for another component, and by adding the reset here you are changing some of the properties of the main component, such as margins, paddings, etc. 
Is this desired behavior?

2022-10-12 08:22 UTC, closed without merging