fix(styles): add shellbar title focus
SAP/fundamental-styles pull request #3835
Opened 2022-08-29 14:41 UTC by hardl

fixes shellbar title focus, similar to https://github.com/SAP/fundamental-styles/pull/3730

2022-08-30 17:35 UTC, mikerodonnell89 commented
I think the focus outline may be the incorrect color, would think it should be white both for the title and for the logo

2022-08-30 18:45 UTC, hardl commented
IDK, I just did copy&paste :D

2022-09-08 11:37 UTC, platon-rov approved these changes

2022-09-12 17:19 UTC, g-cheishvili approved these changes

2022-09-12 21:13 UTC, mikerodonnell89 requested changes
Then I think instead let's do:

```
  &__logo, &__title {
    outline-color: var(--fdShellbar_Button_Outline_Color);
    outline-width: var(--sapContent_FocusWidth);
    outline-style: var(--sapContent_FocusStyle);
}
```

And remove `@include fd-fiori-focus(0);` from `&__title` and `&__logo`

2022-09-23 13:45 UTC, InnaAtanasova approved these changes

2022-10-04 23:24 UTC, mikerodonnell89 approved these changes

2022-10-04 23:24 UTC, merged