fix(styles): notification text containers should use margin, not padding, for spacing
SAP/fundamental-styles pull request #3936
Opened 2022-10-17 20:37 UTC by mikerodonnell89

fixes #3910 

Before (note the 'p' and 'g' letters above the highlighted element):
<img width="420" alt="Screen Shot 2022-10-17 at 2 37 00 PM" src="https://user-images.githubusercontent.com/2471874/196278262-b1678167-8b25-4589-9626-c4b2b4e52f89.png">

After:
<img width="669" alt="Screen Shot 2022-10-17 at 2 36 22 PM" src="https://user-images.githubusercontent.com/2471874/196278380-fc3766d9-c569-4ed0-b346-eadf27383bad.png">

2022-10-18 17:59 UTC, InnaAtanasova approved these changes

2022-10-20 08:49 UTC, platon-rov approved these changes

2022-10-21 00:51 UTC, droshev requested changes
@mikerodonnell89 can we run chromatic?

2022-10-24 16:23 UTC, mikerodonnell89 commented
> @mikerodonnell89 can we run chromatic?

done

2022-10-26 16:45 UTC, droshev approved these changes

2022-10-26 19:26 UTC, merged