feat(styles): introduce message popover component [ci visual]
SAP/fundamental-styles pull request #3937
Opened 2022-10-19 08:47 UTC by N1XUS

## Related Issue
Relates https://github.com/SAP/fundamental-ngx/issues/8329

## Description
Added new components:
- Message List
- Message View
- Message Popover

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.
>
> To see examples of which screenshots to include, go to [Screenshot Examples](https://github.com/SAP/fundamental-styles/wiki/Pull-Request-Screenshot-Examples).
<img width="473" alt="image" src="https://user-images.githubusercontent.com/6586561/196642222-80299f33-28c7-41cf-bc18-88ff01358914.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/6586561/196642257-820f551b-fe97-4750-bb0b-e560022e52be.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/6586561/196642585-cc6d1834-4475-43de-925f-f82627b74f18.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/6586561/196642609-eb3ecf47-f40c-4ee5-a7a4-49ca0bbf0c2b.png">

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [x] Text elements follow the truncation rules
- [x] hover state of the element follow design spec
- [x] focus state of the element follow design spec
- [x] active state of the element follow design spec
- [x] selected state of the element follow design spec
- [x] selected hover state of the element follow design spec
- [x] pressed state of the element follow design spec
- [x] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [x] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [x] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [x] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [x] tested Storybook examples with "CSS Resources" `normalize` option 
- [x] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [x] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [x] Storybook documentation has been created/updated
- [x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

2022-10-19 09:16 UTC, platon-rov requested changes
Popover should a bit overlap its trigger in Fiori 3
<img width="100" alt="image" src="https://user-images.githubusercontent.com/20265336/196647797-0b2711c5-21fd-49e1-905d-3190cf5e0c76.png">

Read more should be under the next, not under the icon
<img width="212" alt="image" src="https://user-images.githubusercontent.com/20265336/196648239-74256b85-0895-4be9-8c8d-348b013ddde2.png">

In details mode we should see back button in header
Let's add example of message popover in details mode so we can track its visuals in chromatic
<img width="380" alt="image" src="https://user-images.githubusercontent.com/20265336/196648577-b5d61975-6c47-4291-af37-59e5c0ca9cd3.png">

Header elements sticked to the border in HC themes
<img width="449" alt="image" src="https://user-images.githubusercontent.com/20265336/196649701-6cf18d55-ef2d-4d05-9038-8832072165d4.png">

Icons should be filled in Fiori HC themes, not outlined
<img width="124" alt="image" src="https://user-images.githubusercontent.com/20265336/196649995-36489393-3205-4100-ba52-14f206d7885f.png">

2022-10-19 09:16 UTC, platon-rov commented on src/styles/mixins/list/_list-message-view.scss
> +      &:active {
`fd-active` mixin

2022-10-19 11:06 UTC, N1XUS commented
> Popover should a bit overlap its trigger in Fiori 3 Curr: <img alt="image" width="79" src="https://user-images.githubusercontent.com/20265336/196650550-c6016abd-940a-42d2-89d0-dbac7d2fe95e.png"> Specs: <img alt="image" width="100" src="https://user-images.githubusercontent.com/20265336/196647797-0b2711c5-21fd-49e1-905d-3190cf5e0c76.png">
> 
> Read more should be under the next, not under the icon Curr: <img alt="image" width="144" src="https://user-images.githubusercontent.com/20265336/196650620-3ac9f680-226a-4e3f-8775-b4e76e2f48e7.png"> Specs: <img alt="image" width="212" src="https://user-images.githubusercontent.com/20265336/196648239-74256b85-0895-4be9-8c8d-348b013ddde2.png">
> 
> In details mode we should see back button in header Let's add example of message popover in details mode so we can track its visuals in chromatic Specs: <img alt="image" width="380" src="https://user-images.githubusercontent.com/20265336/196648577-b5d61975-6c47-4291-af37-59e5c0ca9cd3.png">
> 
> Header elements sticked to the border in HC themes <img alt="image" width="449" src="https://user-images.githubusercontent.com/20265336/196649701-6cf18d55-ef2d-4d05-9038-8832072165d4.png">
> 
> Icons should be filled in Fiori themes, not outlined Curr: <img alt="image" width="109" src="https://user-images.githubusercontent.com/20265336/196650818-876656ae-a206-4963-8623-bcc20c56cb30.png"> Specs: <img alt="image" width="124" src="https://user-images.githubusercontent.com/20265336/196649995-36489393-3205-4100-ba52-14f206d7885f.png">

Hey Platon. Thank you for your review. Couple of notes from my side:
- Filled icons - It's a general issue with the Object Status for Fiori theme. We had an issue for that somewhere, so it's not relevant for this particular task since this component is a combination of existing components with small style additions
- Overlapping popover: UI5's version doesn't overlap, and, frankly, I think such overlapping might be harmful in ngx

2022-10-19 14:34 UTC, platon-rov approved these changes

2022-10-20 20:17 UTC, N1XUS commented on src/styles/message-popover.scss
> +@mixin _fd-message-popover-trigger($colors, $state) {
@InnaAtanasova following button mixins that are limited to the button component only

2022-10-20 20:22 UTC, InnaAtanasova commented on src/styles/_message-view.scss
> +    padding: 1rem 1rem 1rem 3.5rem;
<img width="482" alt="Screen Shot 2022-10-20 at 4 21 46 PM" src="https://user-images.githubusercontent.com/39598672/197050292-04f31480-2e07-4d69-9025-6e127acf70aa.png">

2022-10-20 20:41 UTC, InnaAtanasova commented
Missing truncation rules for the title and subtitle.
Fund-styles:
<img width="1020" alt="Screen Shot 2022-10-20 at 4 39 51 PM" src="https://user-images.githubusercontent.com/39598672/197053627-58e95a1d-8ce5-458c-b62e-a729b4160b0a.png">

UI5:
<img width="539" alt="Screen Shot 2022-10-20 at 4 40 11 PM" src="https://user-images.githubusercontent.com/39598672/197053662-93ecc711-4d13-4a50-a8d6-394afb88cc3a.png">

2022-10-21 08:03 UTC, N1XUS commented on src/styles/_message-view.scss
> +  @include fd-reset();
Scrollbar aren't overwriting necessary parts of the message view. Technically, message view can be also used without fd-scrollbar, thus it also should contain own reset

2022-10-21 16:08 UTC, InnaAtanasova approved these changes

2022-10-21 16:08 UTC, InnaAtanasova commented
Great job, Denis!

2022-10-24 14:24 UTC, merged