chore(docs): doc-ui readme update
SAP/fundamental-styles pull request #3986
Opened 2022-10-31 14:07 UTC by ynnenu

4. Documentation
- [ ] Storybook documentation has been created/updated

2022-11-03 11:04 UTC, platon-rov commented on .gitignore
> -.DS_Store
Probable deleted by mistake.

2022-11-08 20:56 UTC, InnaAtanasova approved these changes

2022-11-14 12:47 UTC, g-cheishvili commented on packages/doc-ui/README.md
> +
no

2022-11-14 12:48 UTC, g-cheishvili requested changes

2022-11-14 12:48 UTC, g-cheishvili commented on packages/doc-ui/README.md
> +## Running Unit Tests
It is not published

2022-11-14 12:48 UTC, g-cheishvili commented on packages/doc-ui/README.md
> +
Excessive info

2022-11-17 19:44 UTC, platon-rov reviewed
Seems like we have unified PR https://github.com/SAP/fundamental-styles/pull/4018 for all the readmes, should we then keep this one?

2022-11-22 16:13 UTC, closed without merging