feat(styles): introduce variant management styling [ci visual]
SAP/fundamental-styles pull request #4031
Opened 2022-11-20 10:01 UTC by N1XUS

## Related Issue
relates https://github.com/SAP/fundamental-ngx/issues/5639

## Description
Added missing styling for variant management component
## Screenshots
![image](https://user-images.githubusercontent.com/6586561/202895978-ea635bdf-2d5e-4914-99b3-621ae1d2e6e6.png)
![image](https://user-images.githubusercontent.com/6586561/202895982-f0a0ab15-0456-4a55-8f6b-7a175a0daf22.png)

### After:

#### Please check whether the PR fulfills the following requirements

2022-11-21 12:56 UTC, g-cheishvili commented
I do not see any stories for this. Is it intentional?

2022-11-25 10:16 UTC, platon-rov commented on packages/styles/src/variant-management.scss
> +    display: flex;
`@include fd-flex()`

2022-11-25 20:03 UTC, InnaAtanasova requested changes
Please add some examples in the documentation.

2022-11-25 20:03 UTC, InnaAtanasova commented on packages/styles/src/variant-management.scss
> +    margin-right: 0.125rem;
same as above. You need to handle RTL

2022-11-25 20:03 UTC, InnaAtanasova commented on packages/styles/src/variant-management.scss
> +    justify-content: center;
please use this mixin:
```
@mixin fd-flex-horizontal-center {
  display: flex;
  justify-content: center;
  @content;
}
```

2022-11-25 20:03 UTC, InnaAtanasova commented on packages/styles/src/theming/common/variant-management/_sap_horizon.scss
> +  --fdVariantManagementCustomDirtyLabelSize: var(--sapFontSmallSize);
`--fdVariantManagementCustomDirtyLabelSize: var(--sapFontSmallSize);` is the same in Quartz and Horizon. Why is it in the theming folder?

2022-11-25 20:03 UTC, InnaAtanasova commented on packages/styles/src/variant-management.scss
> +  &__header {
missing reset?

2022-12-05 16:59 UTC, InnaAtanasova requested changes

2022-12-05 16:59 UTC, InnaAtanasova commented on packages/styles/stories/Components/variant-management/variant-management.stories.js
> +      <i role="presentation" glyph="slim-arrow-down" class="sap-icon--slim-arrow-down"></i>
What is `glyph="slim-arrow-down"`?

2022-12-05 17:09 UTC, InnaAtanasova commented on packages/styles/src/variant-management.scss
> +      cursor: pointer;
since you are using flex you can add `gap: 0.125rem` and then get rid of margin-right of the child elements

2022-12-05 17:09 UTC, InnaAtanasova commented on packages/styles/src/variant-management.scss
> +    @include fd-set-margin-right($title-margin);
same here

2022-12-06 07:07 UTC, N1XUS commented on packages/styles/stories/Components/variant-management/variant-management.stories.js
> +      <i role="presentation" glyph="slim-arrow-down" class="sap-icon--slim-arrow-down"></i>
Sorry, took html from ngx :)

2022-12-06 07:10 UTC, N1XUS commented on packages/styles/src/variant-management.scss
> +  .#{$block} &__title {
We are using fd-title for this element for correct sizing, and we add `fd-variant-management__title` modifier class to it to adjust colors according to the specs

2022-12-06 20:10 UTC, InnaAtanasova approved these changes

2022-12-07 07:44 UTC, merged