fix(styles): add fix for margin-bottom of Select [ci visual]
SAP/fundamental-styles pull request #4079
Opened 2022-12-05 18:53 UTC by InnaAtanasova

## Related Issue
Closes https://github.com/SAP/fundamental-styles/issues/3589

## Description
The inputs (by design) have margins top and bottom of 0.25rem. When the inputs are controls, aka open/close a menu, which is the case of Select component, the bottom margin should disappear. In recent fix the margin-bottom of the Select control was set to 0, which makes the control not vertically aligned when positioned with other controls. 
The current fix sets the margin-bottom to 0 only when the input has aria-expanded set to true or the class `is-expanded` is added to the element

2022-12-05 19:33 UTC, droshev approved these changes

2022-12-07 14:36 UTC, N1XUS requested changes

2022-12-07 14:36 UTC, N1XUS commented on packages/styles/src/select.scss
> +    &[aria-expanded="true"] {
You can use `fd-expanded` mixin here :)

2022-12-08 16:15 UTC, InnaAtanasova commented on packages/styles/src/select.scss
> +    &[aria-expanded="true"] {
true! Thank you. It's now fixed

2022-12-09 20:07 UTC, platon-rov approved these changes

2022-12-13 15:22 UTC, merged