fix(docs): broken examples, defect hunting 103
SAP/fundamental-styles pull request #4122
Opened 2022-12-19 12:57 UTC by platon-rov

## Related Issue

Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355405788
Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355386561
Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355372529

## Description

Various broken examples fixes.

## Screenshots

### Before:
Dynamic Page
![image](https://user-images.githubusercontent.com/20265336/208431078-c7427f8e-f701-4b4b-bc5e-5f332d883c26.png)

Table
![image](https://user-images.githubusercontent.com/20265336/208445519-85e345c5-98af-401b-9452-8dfeea246778.png)

Object Status
![image](https://user-images.githubusercontent.com/20265336/208462076-5ec8ae32-973c-4ced-9326-fbb191d3f2ca.png)

### After:
Dynamic Page
<img width="152" alt="CleanShot 2022-12-19 at 13 56 34@2x" src="https://user-images.githubusercontent.com/20265336/208431155-102f2acf-2b58-4856-9934-18c342f672b3.png">

Table
<img width="600" alt="CleanShot 2022-12-19 at 15 14 13@2x" src="https://user-images.githubusercontent.com/20265336/208445422-66e90ebc-9d79-4c45-a136-79660ccf18e5.png">
<img width="538" alt="CleanShot 2022-12-19 at 15 14 40@2x" src="https://user-images.githubusercontent.com/20265336/208445458-e35b6451-ca90-4635-b57a-30667193b164.png">

Object Status
<img width="373" alt="CleanShot 2022-12-19 at 16 33 25@2x" src="https://user-images.githubusercontent.com/20265336/208462130-0d822ba4-facc-4393-82b3-1251a93eafbf.png">

2022-12-19 19:16 UTC, mikerodonnell89 approved these changes

2022-12-19 19:20 UTC, InnaAtanasova approved these changes

2022-12-19 20:28 UTC, g-cheishvili requested changes
I believe quote changes were not intended and PR needs snapshots update

2022-12-26 14:38 UTC, g-cheishvili approved these changes

2022-12-26 15:19 UTC, merged