fix(styles): add Horizon delta for User Menu [ci visual]
SAP/fundamental-styles pull request #4168
Opened 2023-01-10 20:52 UTC by InnaAtanasova

## Related Issue
Closes https://github.com/SAP/fundamental-styles/issues/4091

2023-01-11 17:18 UTC, mikerodonnell89 requested changes
I would think when there is a footer present, the last list item should not have bottom border radii when focused:

<img width="349" alt="Screenshot 2023-01-11 at 10 17 46 AM" src="https://user-images.githubusercontent.com/2471874/211872981-e1cb1627-6000-46e6-8476-5b4a960f3a93.png">

2023-01-12 11:08 UTC, platon-rov reviewed
Why do we have such big spacing?

<img width="310" alt="image" src="https://user-images.githubusercontent.com/20265336/212050505-5ea6bc0f-5b9a-4fe4-99c4-b8bc69e99505.png">

Looks like in wiki it's 8px always
<img width="354" alt="image" src="https://user-images.githubusercontent.com/20265336/212051007-67cc25f5-0597-49b7-b2fb-9c9efa92e456.png">

Plus, rounding of focus outline seems redundant when there are paddings.

2023-01-13 15:14 UTC, InnaAtanasova commented
> https://deploy-preview-4168--fundamental-styles.netlify.app



> I would think when there is a footer present, the last list item should not have bottom border radii when focused:
> 
> <img alt="Screenshot 2023-01-11 at 10 17 46 AM" width="349" src="https://user-images.githubusercontent.com/2471874/211872981-e1cb1627-6000-46e6-8476-5b4a960f3a93.png">

This is List component used inside User Menu. The fix should be coming from List, not this component (out of this PR scope)

2023-01-13 15:19 UTC, InnaAtanasova commented
> Why do we have such big spacing?
> 
> <img alt="image" width="310" src="https://user-images.githubusercontent.com/20265336/212050505-5ea6bc0f-5b9a-4fe4-99c4-b8bc69e99505.png">
> 
> Looks like in wiki it's 8px always <img alt="image" width="354" src="https://user-images.githubusercontent.com/20265336/212051007-67cc25f5-0597-49b7-b2fb-9c9efa92e456.png">
> 
> Plus, rounding of focus outline seems redundant when there are paddings.

For the rounded corners: This is List component used inside User Menu. The fix should be coming from List, not this component (out of this PR scope). If we fix it only here, other components that have similar case will also have to fix it.

As for the spacing, the Popover paddings are these:
<img width="540" alt="Screenshot 2023-01-13 at 10 19 01 AM" src="https://user-images.githubusercontent.com/39598672/212355096-751ffcd9-78c8-41f6-aa54-25378fcd8739.png">

2023-01-13 15:25 UTC, InnaAtanasova commented
created an issue for the rounded corners: https://github.com/SAP/fundamental-styles/issues/4173

2023-01-13 16:46 UTC, InnaAtanasova commented
> I would think when there is a footer present, the last list item should not have bottom border radii when focused:
> 
> <img alt="Screenshot 2023-01-11 at 10 17 46 AM" width="349" src="https://user-images.githubusercontent.com/2471874/211872981-e1cb1627-6000-46e6-8476-5b4a960f3a93.png">

fixed

2023-01-17 23:59 UTC, mikerodonnell89 approved these changes

2023-01-24 23:01 UTC, mikerodonnell89 requested changes

2023-01-24 23:01 UTC, mikerodonnell89 commented on packages/styles/src/user-menu.scss
> +      border-radius: 0 !important;
Probably first-child too?
<img width="383" alt="Screenshot 2023-01-24 at 4 01 24 PM" src="https://user-images.githubusercontent.com/2471874/214440261-b100997e-cf92-471d-93c2-2f9ddfc1a140.png">

2023-01-25 15:36 UTC, InnaAtanasova commented on packages/styles/src/user-menu.scss
> +      border-radius: 0 !important;
fixed

2023-01-25 16:44 UTC, mikerodonnell89 approved these changes

2023-01-25 19:20 UTC, merged