fix(styles): update tile title font size [ci visual]
SAP/fundamental-styles pull request #4516
Opened 2023-05-08 11:32 UTC by droshev

## Related Issue
Closes SAP/fundamental-styles#4502

update tile title font size

2023-05-08 14:14 UTC, g-cheishvili approved these changes

2023-05-08 17:27 UTC, InnaAtanasova requested changes

2023-05-08 17:27 UTC, InnaAtanasova commented on packages/styles/src/tile.scss
> +    font-size: var(--sapFontHeader6Size);
that's the font-size for small Tile

2023-05-08 20:54 UTC, droshev commented on packages/styles/src/tile.scss
> +    font-size: var(--sapFontHeader6Size);
updated

2023-05-08 21:00 UTC, InnaAtanasova requested changes
The values are the same for all themes in Horizon and all themes in Quartz. You need to put them in the `common` folder and have only 2 files, 1 for Horizon and 1 for Quartz, instead of 9 files

2023-05-08 22:29 UTC, droshev commented
> The values are the same for all themes in Horizon and all themes in Quartz. You need to put them in the `common` folder and have only 2 files, 1 for Horizon and 1 for Quartz, instead of 9 files

done

2023-05-09 12:43 UTC, InnaAtanasova approved these changes

2023-05-10 19:24 UTC, merged