fix(styles): fix readonly textarea [ci visual]
SAP/fundamental-styles pull request #5326
Opened 2024-04-25 11:56 UTC by droshev

fix readonly textarea part of https://github.com/SAP/fundamental-ngx/issues/11809

2024-04-25 14:53 UTC, InnaAtanasova requested changes
There's a border bottom that shouldn't be there
<img width="1152" alt="Screenshot 2024-04-25 at 10 51 57 AM" src="https://github.com/SAP/fundamental-styles/assets/39598672/3a69b897-f7f1-4341-8df0-5fd0c8638111">

2024-04-25 14:53 UTC, InnaAtanasova commented on packages/styles/src/textarea.scss
> +    padding: 0.375rem 0.125rem 0.5rem;
please use padding-inline and padding-block

2024-04-25 19:16 UTC, droshev commented
> There's a border bottom that shouldn't be there <img alt="Screenshot 2024-04-25 at 10 51 57 AM" width="1152" src="https://private-user-images.githubusercontent.com/39598672/325659421-3a69b897-f7f1-4341-8df0-5fd0c8638111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNzI4NjcsIm5iZiI6MTcxNDA3MjU2NywicGF0aCI6Ii8zOTU5ODY3Mi8zMjU2NTk0MjEtM2E2OWI4OTctZjdmMS00MzQxLThkZjAtNWZkMGM4NjM4MTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE5MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMmFkMjU4YTg4Y2ExYWE1NjAxNWY0YjExODVkY2NmZmQ3YWYwMjc5ZjFhZDVjNzJiODNjN2M1Zjg2Mzk1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zceVuv59tfzJkVaIekv8bToDrPNsXO1vIz__geDoTsE">

updated

2024-05-01 11:49 UTC, InnaAtanasova approved these changes

2024-05-01 15:35 UTC, merged